### PR TITLE
Add middleware

### LINKED ISSUE #4: Should provide a middleware?
I think middleware is the commonest way.

``` js
module.exports.middleware = function () {
  return function* (next) {
    this.request.method = overrideMethod.call(this, this.request.body)
    yield* next;
  }
}
```

### PR DESCRIPTION
**Pull request by fengmk2**
fixed #4 
## Usage

``` js
var bodyParser = require('koa-body-parser')
var override = require('koa-override-method')

app.use(bodyParser())
app.use(override())
```

### CODE REVIEW

**Comment by jonathanong** [comment]
i don't use this library so you can do this :)

**Comment by tj** [comment]
hmm kinda weird to do both in one lib IMO

**Comment by fengmk2** [comment]
agree with @visionmedia , maybe we should change this module to a koa middleware, not a utils module.

**Comment by fengmk2** [comment]
I change this module to middleware, not a function utility.

**Comment by jonathanong** [comment]
It shouldn't only be middleware because body parsing shouldn't be middleware either

**Comment by fengmk2** [comment]
Maybe I should create a new middleware module deps on this.

**Comment by zj8487** [comment]
@fengmk2 
may you tell me where can i find the koa middleware for this util?

**Comment by fengmk2** [comment]
@zj8487 this one https://www.npmjs.com/package/koa-override ?

**Pull request closed without merging**
